# Generated by Django 5.1.2 on 2026-02-01 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
        ("goods", "0021_alter_productimage_image_alter_products_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="favorite",
            name="session_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "product"),
                name="unique_user_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__isnull", False)),
                fields=("session_key", "product"),
                name="unique_session_product",
            ),
        ),
        migrations.AlterModelTable(
            name="favorite",
            table="favorite",
        ),
    ]
