# Generated by Django 5.1.2 on 2024-11-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "goods",
            "0002_alter_categories_options_alter_categories_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={
                "verbose_name": "Категорію",
                "verbose_name_plural": "Категорії",
            },
        ),
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукти",
            },
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Назва"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.categories",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Знижка в %",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="goods_images",
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Назва"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Ціна",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Кількість"
            ),
        ),
    ]
