# Generated by Django 5.1.2 on 2024-11-19 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "goods",
            "0003_alter_categories_options_alter_products_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, verbose_name="Назва характеристики"
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=255, verbose_name="Значення"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="goods.products",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика продукту",
                "verbose_name_plural": "Характеристики продукту",
                "db_table": "product_attribute",
            },
        ),
    ]
