# Generated by Django 5.1.2 on 2024-11-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_productattribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={
                "ordering": ("id",),
                "verbose_name": "Категорію",
                "verbose_name_plural": "Категорії",
            },
        ),
    ]
