# Generated by Django 5.1.2 on 2025-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0007_categories_name_en_categories_name_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="currency",
            field=models.CharField(
                choices=[("UAH", "Грн"), ("USD", "Долар")],
                default="UAH",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
    ]
