# Generated by Django 5.1.2 on 2025-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0009_exchangerate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExchangeRate",
        ),
        migrations.AddField(
            model_name="products",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=1.0,
                max_digits=10,
                null=True,
                verbose_name="Курс валют",
            ),
        ),
    ]
