# Generated by Django 5.1.2 on 2025-03-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0013_exchangerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="price_in_uah",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Ціна в гривнях",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="price_in_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Ціна в доларах",
            ),
        ),
    ]
