# Generated by Django 5.1.2 on 2026-01-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0016_products_discounted_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="goods_images", verbose_name="Зображення"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="goods.products",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення продукту",
                "verbose_name_plural": "Зображення продукту",
                "db_table": "product_image",
                "ordering": ("order",),
            },
        ),
    ]
