# Generated by Django 5.1.2 on 2026-01-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0017_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "1-е зображення"),
                    (1, "2-е зображення"),
                    (2, "3-є зображення"),
                    (3, "4-е зображення"),
                ],
                default=0,
                verbose_name="Порядок",
            ),
        ),
    ]
