# Generated by Django 5.1.2 on 2026-01-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0018_alter_productimage_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=1.0,
                max_digits=10,
                null=True,
                verbose_name="Курс валют USD->UAH",
            ),
        ),
    ]
