# Generated by Django 5.1.2 on 2026-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0019_alter_products_exchange_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("ready_to_ship", "Готовий до відправлення"),
                    ("last_item", "Останній товар!"),
                    ("out_of_stock", "Немає в наявності"),
                ],
                default="ready_to_ship",
                max_length=20,
                verbose_name="Статус наявності",
            ),
        ),
    ]
