# Generated by Django 5.1.2 on 2026-01-29 08:16

import apps.goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0020_products_availability_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.goods.models.product_image_path,
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.goods.models.product_image_path,
                verbose_name="Зображення",
            ),
        ),
    ]
