# Generated by Django 5.1.2 on 2024-11-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ("id",),
                "verbose_name": "Кошик",
                "verbose_name_plural": "Кошик",
            },
        ),
    ]
