# Generated by Django 5.1.2 on 2025-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField()),
            ],
            options={
                "verbose_name": "відгук",
                "verbose_name_plural": "відгуки",
                "db_table": "user_feedback",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
