# Generated by Django 5.1.2 on 2026-08-11 15:20

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.users.models.user_image_path,
                verbose_name="Аватар",
            ),
        ),
    ]
