# Generated by Django 5.1.2 on 2024-12-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_categories_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="Знижка в %"
            ),
        ),
    ]
