# Generated by Django 5.1.2 on 2025-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_alter_products_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="name_en",
            field=models.CharField(
                max_length=150, null=True, unique=True, verbose_name="Назва"
            ),
        ),
        migrations.AddField(
            model_name="categories",
            name="name_uk",
            field=models.CharField(
                max_length=150, null=True, unique=True, verbose_name="Назва"
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="key_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Назва характеристики"
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="key_uk",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Назва характеристики"
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Значення"
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_uk",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Значення"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="products",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="products",
            name="name_en",
            field=models.CharField(
                max_length=150, null=True, unique=True, verbose_name="Назва"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="name_uk",
            field=models.CharField(
                max_length=150, null=True, unique=True, verbose_name="Назва"
            ),
        ),
    ]
