# Generated by Django 5.1.2 on 2025-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0010_delete_exchangerate_products_exchange_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        default="USD",
                        max_length=3,
                        verbose_name="Базова валюта",
                    ),
                ),
                (
                    "target_currency",
                    models.CharField(
                        default="UAH",
                        max_length=3,
                        verbose_name="Цільова валюта",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Курс валют",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Оновлено"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="products",
            name="exchange_rate",
        ),
    ]
