# Generated by Django 5.1.2 on 2025-03-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0012_delete_exchangerate_products_exchange_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        max_length=3, verbose_name="Базова валюта"
                    ),
                ),
                (
                    "target_currency",
                    models.CharField(
                        max_length=3, verbose_name="Цільова валюта"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Курс обміну",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Оновлено"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс валют",
                "verbose_name_plural": "Курси валют",
                "unique_together": {("base_currency", "target_currency")},
            },
        ),
    ]
