# Generated by Django 5.1.2 on 2025-03-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0014_products_price_in_uah_products_price_in_usd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="price_in_uah",
        ),
    ]
