# Generated by Django 5.1.2 on 2025-03-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0015_remove_products_price_in_uah"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="discounted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Ціна зі знижкою",
            ),
        ),
    ]
