# Generated by Django 5.1.2 on 2025-05-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "В обробці"),
                    ("shipped", "Відправлено"),
                    ("delivered", "Доставлено"),
                ],
                default="processing",
                max_length=50,
                verbose_name="Статус замовлення",
            ),
        ),
    ]
